name: Python Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-22.04  # Вказуємо явну версію Ubuntu

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install WebDriver dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
            xvfb \
            libnss3 \
            libxss1 \
            libappindicator1 \
            libindicator7 \
            fonts-liberation \
            libatk-bridge2.0-0 \
            libgtk-3-0 \
            libxshmfence1

    - name: Run tests
      run: |
        pytest tests/ --headless --browser=chrome